In [1]:
import numpy as np
arr = np.array([17, 18, 19, 20, 21])

In [2]:
print(arr.argsort()[:3])  #Lowest 3 (17, 18, 19)

[0 1 2]


In [3]:
print(arr.argsort()[:3][::-1])  #Lowest 3 (19, 18, 17)

[2 1 0]


In [4]:
print(arr.argsort()[-3:])  #Highest 3 (19, 20, 21)

[2 3 4]


In [5]:
print(arr.argsort()[-3:][::-1])  #Highest 3 (21, 20, 19)

[4 3 2]


In [6]:
17/3

5.666666666666667

In [7]:
17//3

5