In [35]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [36]:
M = DataFrame({
    "ColA":[1, 1, 1, 1, 1, 1, 1, 1],
    "ColB":[1, 1, 1, 1, 2, 2, 2, 2],
    "ColC":[1, 1, 2, 2, 3, 3, 4, 4]
})

In [37]:
M

ColA  ColB  ColC
0     1     1     1
1     1     1     1
2     1     1     2
3     1     1     2
4     1     2     3
5     1     2     3
6     1     2     4
7     1     2     4

In [38]:
M.duplicated()

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7     True
dtype: bool

In [39]:
M.drop_duplicates("ColB")

ColA  ColB  ColC
0     1     1     1
4     1     2     3

In [40]:
l = Series([2,3,np.nan,7,"The Hobbit"])

In [41]:
l

0             2
1             3
2           NaN
3             7
4    The Hobbit
dtype: object

In [42]:
l.isnull()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [43]:
l.isnull().values.any()

True

In [44]:
l.isnull().sum()

1

In [45]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame
Nan = np.nan
m = DataFrame({ "A" : [1, Nan, Nan],
               "B" :  [2, Nan, 3]
              })
m.isnull()

A      B
0  False  False
1   True   True
2   True  False

In [46]:
m.isnull().values.any()

True

In [47]:
m.isnull().sum()

A    2
B    1
dtype: int64

In [48]:
m.isnull().sum().sum()

3

In [49]:
m

A    B
0  1.0  2.0
1  NaN  NaN
2  NaN  3.0

In [50]:
m.fillna(4)

A    B
0  1.0  2.0
1  4.0  4.0
2  4.0  3.0

In [51]:
m

A    B
0  1.0  2.0
1  NaN  NaN
2  NaN  3.0

In [52]:
for a in range(20):
    print(a)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [53]:
k = np.arange(5)
print(k)
k = np.arange(10)
print(k)
k = np.arange(2,10)
print(k)
k = np.arange(2,20,2)
print(k)
print(np.arange(2,8))

[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]
[2 3 4 5 6 7]


In [54]:
k = np.arange(8).reshape(4,2)
k

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [55]:
k = DataFrame(np.arange(8).reshape(4,2))
k

0  1
0  0  1
1  2  3
2  4  5
3  6  7

In [56]:
k1 = DataFrame(np.arange(12).reshape(4,3))
k1

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [57]:
pd.concat([k,k1], axis=1)

0  1  0   1   2
0  0  1  0   1   2
1  2  3  3   4   5
2  4  5  6   7   8
3  6  7  9  10  11

In [58]:
m = pd.concat([k,k1])

In [59]:
m

0   1     2
0  0   1   NaN
1  2   3   NaN
2  4   5   NaN
3  6   7   NaN
0  0   1   2.0
1  3   4   5.0
2  6   7   8.0
3  9  10  11.0

In [60]:
z = m.drop([0,2,3])
z

0  1    2
1  2  3  NaN
1  3  4  5.0

In [61]:
z.drop([0,2],axis=1)

1
1  3
1  4

In [62]:
k1

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [63]:
l = Series(np.arange(6))
l.name = "A"
l

0    0
1    1
2    2
3    3
4    4
5    5
Name: A, dtype: int32

In [64]:
j = DataFrame.join(k1, l)

In [65]:
j

0   1   2  A
0  0   1   2  0
1  3   4   5  1
2  6   7   8  2
3  9  10  11  3

In [66]:
j.sort_values(by="A", ascending = [True])

0   1   2  A
0  0   1   2  0
1  3   4   5  1
2  6   7   8  2
3  9  10  11  3

In [67]:
j.sort_values(by="A", ascending = [False])

0   1   2  A
3  9  10  11  3
2  6   7   8  2
1  3   4   5  1
0  0   1   2  0

In [68]:
j.sort_values(by=1, ascending = [False])

0   1   2  A
3  9  10  11  3
2  6   7   8  2
1  3   4   5  1
0  0   1   2  0